[package]
name = "dfir-timeline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apache-avro = {version="0.14", features = ["derive"]}
serde = {version="1.0", features = ["derive"]}
serde_json = "1.0"
chrono = {version="0.4", features=["serde"]}
chrono-tz = "0.8"
bodyfile = "0.1"
log = "0.4"
lazy_static = "1.4"