[package]
name = "flow-record"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rmp = "0.8"
rmp-serde = "1.3.0"
serde = {version="1.0", features = ["derive"]}
serde_json = "1.0"
chrono = {version="0.4", features=["serde"]}
chrono-tz = "0.10"
bodyfile = "0.1"
log = "0.4"
recorddescriptor_derive = {path="recorddescriptor_derive"}
once_cell = "1.18"
