[package]
name = "flow-record-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = {version="2.0", features=["extra-traits"] }
quote = "1.0"
proc-macro2 = "1"
serde = {version="1.0", features = ["derive"]}
rmp = "0.8"
rmp-serde = {version="1.1"}
serde_bytes = "0.11"